experiment:
  name: gph

plotting:
  enabled: false
  save: false
  show_test: false

model:
  in_dim: 5
  out_dim: 5
  num_hidden: 3
  hidden_dim: 100
  gamma: 1.0
  bias: false
  seed: 0

training:
  lr: 0.0001
  batch_size: null
  optimizer: SGD
  optimizer_params: null
  criterion: MSELoss
  batch_seed: 0

data:
  train_samples: 500
  test_samples: null
  data_seed: 0
  online: false
  noise_std: 0.0
  params:
    matrix: diagonal
    scale: 10.0

metrics:
  # - trace_covariances:
  #     chunks: 2

metric_data:
  mode: population
  holdout_size: null

callbacks: []

max_steps: 10000
num_evaluations: 250