defaults:
  - paths
  - _self_

experiment:
  name: "diagonal_teacher"

plotting:
  enabled: true
  show: false
  save: true
  show_test: false

model:
  in_dim: 5
  out_dim: 5
  num_hidden: 3
  hidden_dim: 50
  gamma: 1.5
  bias: false
  seed: 0

training:
  lr: 0.0005
  batch_size: null 
  optimizer: "SGD"
  optimizer_params: null
  criterion: "MSELoss"
  batch_seed: 0

data:
  train_samples: 100
  test_samples: null
  data_seed: 0
  online: false
  noise_std: 0.0
  params:
    matrix: "diagonal"
    scale: 10

max_steps: 2500
stop_threshold: null
evaluate_every: 1
metrics: []
metric_data:
  mode: "population"
  holdout_size: null
metric_chunks: 1
callbacks: []