defaults:
  - paths
  - _self_

experiment:
  name: "gph"

plotting:
  enabled: true
  show: false
  save: true

model:
  in_dim: 5
  out_dim: 5
  num_hidden: 3
  hidden_dim: 128
  gamma: 1.0
  bias: false
  seed: 0

training:
  lr: 0.0001
  batch_size: null
  optimizer: "SGD"
  optimizer_params: null
  criterion: "MSELoss"
  batch_seed: 0

data:
  num_samples: 500
  test_split: 0.1
  data_seed: 0
  online: false
  noise_std: 0.0
  params:
    matrix: "diagonal"
    scale: 10.0

max_steps: 20000
evaluate_every: 20
metrics:
  - "grad_norm_squared"
  - "trace_gradient_covariance"
  - "trace_hessian_covariance"
metric_data:
  mode: "population"
  holdout_size: null
callbacks: []
stop_threshold: 10e-9