defaults:
  - gph_paths
  - _self_
  - mode: offline

experiment:
  name: "gph"

plotting:
  enabled: true
  show: false
  save: true
  show_test: true

model:
  in_dim: 5
  out_dim: 5
  num_hidden: 3
  hidden_dim: 100
  gamma: 1.0
  bias: false
  seed: 0

training:
  lr: 0.0001
  batch_size: null
  optimizer: "SGD"
  optimizer_params: null
  criterion: "MSELoss"
  batch_seed: 0

data:
  train_samples: 500
  test_samples: 500
  data_seed: 0
  noise_std: 0.0
  params:
    matrix: "diagonal"
    scale: 10.0

max_steps: ${max_steps_for_gamma:${model.gamma}}
evaluate_every: 20
metrics:
  - "trace_covariances"
metric_chunks: 1
  
callbacks: []
stop_threshold: null