hydra:
  run:
    dir: outputs/comparative/runs/${experiment.name}_${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs/comparative/multiruns/${experiment.name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}